
build: trust

language: node_js

node_js:
  - '8'
  - '6'

sudo: required

install:
  - node

cache:
  node: true
  directories:
    - node_modules

before_script:
  - npm install

script:
  - npm run build
  - npm test
